# Load Items

In [1]:
import json
import pprint

import numpy as np
import scipy.stats as ss
import pandas as pd
pd.set_option('display.max_columns', 100)

import warnings 
warnings.filterwarnings('ignore')

import condense_csv

In [141]:
def get_data(data_path, label_path, valid_size=0.2):
    """
    Get the data, and split it into train and validation.

    :param data_path: path of the data input
    :type  data_path: str
    :param label_path: path of the data label
    :type  label_path: str
    :param test_size: Proportion to split on for the validation size
    :type  test_size: float
    """

    from sklearn.model_selection import train_test_split

    data = pd.read_csv(data_path)
    labels = pd.read_csv(label_path)
    data = condense_csv.compress_X(data)
    labels = condense_csv.compress_labels(labels)

    X_train, X_valid, y_train, y_valid = train_test_split(
        data,
        labels,
        test_size=valid_size,
        random_state=42
    )

    return X_train, X_valid, y_train, y_valid


train_X, valid_X, train_y, valid_y = get_data(
    '../data/train.csv', '../data/train_labels.csv')

memory used before preprocess:  19.00808

date time size before: 3.9798799999999996
date time size after:  0.47528

converting funder                         size:  3.86	->	 0.33
converting installer                      size:  3.64	->	 0.34
converting basin                          size:  4.03	->	 0.06
converting subvillage                     size:  3.85	->	 2.03
converting region                         size:  3.78	->	 0.06
converting lga                            size:  3.83	->	 0.07
converting ward                           size:  3.83	->	 0.34
converting public_meeting                 size:  2.1	->	 0.06
converting recorded_by                    size:  4.75	->	 0.06
converting scheme_management              size:  3.55	->	 0.06
converting scheme_name                    size:  3.15	->	 0.4
converting permit                         size:  2.06	->	 0.06
converting extraction_type                size:  3.84	->	 0.06
converting extraction_type_group          size:  3.85	->	 0.06
converting extraction_type_class          size:  3.84	->	 0.06
converting management                     size:  3.64	->	 0.06
converting management_group               size:  3.97	->	 0.06
converting payment                        size:  4.02	->	 0.06
converting payment_type                   size:  3.89	->	 0.06
converting water_quality                  size:  3.64	->	 0.06
converting quality_group                  size:  3.64	->	 0.06
converting quantity                       size:  3.82	->	 0.06
converting quantity_group                 size:  3.82	->	 0.06
converting source                         size:  3.92	->	 0.06
converting source_type                    size:  3.94	->	 0.06
converting source_class                   size:  3.98	->	 0.06
converting waterpoint_type                size:  4.27	->	 0.06
converting waterpoint_type_group          size:  4.21	->	 0.06

downcasting integers for: ['id', 'gps_height', 'num_private', 'region_code', 'district_code', 'population', 'construction_year']

reduced memory usage for:   id                  from     0.48 to     0.24
reduced memory usage for:   gps_height          from     0.48 to     0.12
reduced memory usage for:   num_private         from     0.48 to     0.12
reduced memory usage for:   region_code         from     0.48 to     0.06
reduced memory usage for:   district_code       from     0.48 to     0.06
reduced memory usage for:   population          from     0.48 to     0.12
reduced memory usage for:   construction_year   from     0.48 to     0.12

available RAM: svmem(total=8589934592, available=1487228928, percent=82.7, used=6600409088, free=386211840, active=3334602752, inactive=1101017088, wired=2164789248)
available RAM: svmem(total=8589934592, available=1487450112, percent=82.7, used=6600613888, free=386433024, active=3335630848, inactive=1101017088, wired=2163965952)

memory used after preprocess:  6.3896

In [4]:
train_X.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
3607,454,50.0,2013-02-27,Dmdd,2092,DMDD,35.426020,-4.227446,Narmo,0,Internal,Bashnet Kati,Manyara,21,1,Babati,Bashinet,160,True,GeoData Consultants Ltd,Water Board,NaN,True,1998,gravity,gravity,gravity,water board,user-group,pay per bucket,per bucket,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
50870,510,0.0,2011-03-17,Cmsr,0,Gove,35.510074,-5.724555,Lukali,0,Internal,Lukali,Dodoma,1,6,Bahi,Lamaiti,0,True,GeoData Consultants Ltd,VWC,NaN,True,0,india mark ii,india mark ii,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
20413,14146,0.0,2011-07-10,Kkkt,0,KKKT,32.499866,-9.081222,Mahakama,0,Lake Rukwa,Chawalikozi,Mbeya,12,6,Mbozi,Ndalambo,0,True,GeoData Consultants Ltd,VWC,NaN,False,0,other,other,other,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,other,other
52806,47410,0.0,2011-04-12,NaN,0,NaN,34.060484,-8.830208,Shule Ya Msingi Chosi A,0,Rufiji,Shuleni,Mbeya,12,7,Mbarali,Chimala,0,True,GeoData Consultants Ltd,VWC,NaN,True,0,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,insufficient,insufficient,river,river/lake,surface,communal standpipe,communal standpipe
50091,1288,300.0,2011-04-05,Ki,1023,Ki,37.032690,-6.040787,Kwa Mjowe,0,Wami / Ruvu,Ngholong,Morogoro,5,1,Kilosa,Chakwale,120,True,GeoData Consultants Ltd,VWC,NaN,True,1997,other,other,other,vwc,user-group,pay when scheme fails,on failure,salty,salty,enough,enough,shallow well,shallow well,groundwater,other,other

In [5]:
train_X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47520 entries, 3607 to 56422
Data columns (total 40 columns):
id                       47520 non-null int32
amount_tsh               47520 non-null float64
date_recorded            47520 non-null datetime64[ns]
funder                   44644 non-null category
gps_height               47520 non-null int16
installer                44631 non-null category
longitude                47520 non-null float64
latitude                 47520 non-null float64
wpt_name                 47520 non-null object
num_private              47520 non-null int16
basin                    47520 non-null category
subvillage               47224 non-null category
region                   47520 non-null category
region_code              47520 non-null int8
district_code            47520 non-null int8
lga                      47520 non-null category
ward                     47520 non-null category
population               47520 non-null int16
public_meeting           44831 non-null category
recorded_by              47520 non-null category
scheme_management        44418 non-null category
scheme_name              24997 non-null category
permit                   45081 non-null category
construction_year        47520 non-null int16
extraction_type          47520 non-null category
extraction_type_group    47520 non-null category
extraction_type_class    47520 non-null category
management               47520 non-null category
management_group         47520 non-null category
payment                  47520 non-null category
payment_type             47520 non-null category
water_quality            47520 non-null category
quality_group            47520 non-null category
quantity                 47520 non-null category
quantity_group           47520 non-null category
source                   47520 non-null category
source_type              47520 non-null category
source_class             47520 non-null category
waterpoint_type          47520 non-null category
waterpoint_type_group    47520 non-null category
dtypes: category(28), datetime64[ns](1), float64(3), int16(4), int32(1), int8(2), object(1)
memory usage: 5.5+ MB

In [6]:
def convert_num_labels_to_cat (df, categories):
    """
    Some columns have integer values, but do not denote any order, 
    so we need to convert them into categories.
    
    :param df: dataframe
    :type  df: pandas.core.frame.DataFrame
    :param categories: list of column names to convert
    :type  categories: list
    """
    
    for cat in categories:
        df[cat] = df[cat].astype('category')
    
    return df

train_X = convert_num_labels_to_cat(train_X, ['region_code', 'district_code'])

In [9]:
# dictz = {
#     'a': [1, 2, 'b'],
#     'd': [5, 6, 11]
# }

# with open('test.json', 'w') as outfile:
#     json.dump (dictz, outfile)
    
# The initial conditions of the class
file = open('starting_info.json')
starting_info = json.load(file)
file.close()
pd.DataFrame(starting_info)

,amount_tsh,basin,construction_year,date_recorded,district_code,extraction_type,extraction_type_class,extraction_type_group,funder,gps_height,id,installer,latitude,lga,longitude,management,management_group,num_private,payment,payment_type,permit,population,public_meeting,quality_group,quantity,quantity_group,recorded_by,region,region_code,scheme_management,scheme_name,source,source_class,source_type,subvillage,ward,water_quality,waterpoint_type,waterpoint_type_group,wpt_name
0,[binning_5],[drop],"[median0, shiftmin]",[finddays],[],[drop],[],[drop],[cbinning_50],[absneg],[drop],[cbinning_100],[drop0],[],[drop0],[],[drop],[drop],[drop],[],[mostcommon],[outlierZ_3],[mostcommon],[],[drop],[],[drop],[],[drop],[mostcommon],[drop],[],[drop],[drop],[drop],[drop],[drop],[drop],[],[drop]
1,Large outliers. Can also try log or box cox,99% corr with region and region has higher cor...,year of 0 does not make sense,Need to convert to days.,,100% corr with extraction_type_group and extra...,,100% corr with extraction_type_group and class...,1900 categories,No way to have negative numbers. Might want to...,All IDs are unique.,2145 categories,Zero latitude is not in tanzania,might want to try dropping it since it has hig...,Zero longitude is not in tanzania,,5% corr with label and 100% corr with management,No description on it and has low correlation w...,100% corr with payment_type,,might want to try dropping because 3% corr wit...,has huge outliers. Might also want to try binn...,Might want to try dropping this since it has 7...,,100% corr with quantity group,,there's only 1 value,,100% corr with region,,"2700 categories, 20000 (2/5 of data) are missi...",,"7% corr with label, and trinary with low freq ...",100% corr with source,way too many categories and is represented by ...,"high corr with lga, has many categories. Try b...",100% corr with quality_group and has lower cor...,100% corr with water_type_group and more noisy,,"Intuitively, there should be no relavancy"

In [10]:
class ColumnOperations:
    """
    A class for representing column operations to be performed for the dataframe
    """
    
    def __init__(self, name, operations, justifications):
        """
        :param name: column name
        :type  name: str
        :param operations: a sequence of operations to be performed on the column
        :type  operations: list
        :param justification: justification for operation
        :type  justification: str
        """
        
        self.name = name
        self.operations = operations
        self.justifications = justifications

In [11]:
def create_col_instances(col_dict):
    """
    Create a list of instances of the column operation class
    
    :param col_dict: dictionary where keys are column names and values are the class attributes
    :type  col_dict: dict
    :returns: list of class instances
    :rtype:   list
    """
    
    col_instances = []
    for col_name, attributes in col_dict.items():
        col_instances.append(ColumnOperations(col_name, attributes[0], attributes[1]))
    return col_instances
        
list_of_classes = create_col_instances(starting_info)
#pprint.pprint (list_of_classes)

In [139]:
def perform_operations(df, col_name, operations):
    """
    Execute operations on a certain column in the dataframe.
                                Operations:      Description:
        Numerics
                                drop             drop the entire column
                                log              perform log transformation on the column
                                box cox          perform box cox transformation on the column
                                drop0            drop all values with zeros in it
                                absneg           absolute value the negatives
                                median0          replace 0 with the median
                                binning_NUM      create NUM amount of bins
                                outlierZ_NUM     remove outliers with z score > NUM
                                shiftmin         subtract the columns by the minimum value

        Datetime
                                finddays         convert datetime to days since the first day

        Categorical/Object
                                cbinning_NUM     create bins where each bin must have occurences of NUM or higher
                                mostcommon       replace nan with most common category

    :param df: dataframe 
    :type  df: pandas.core.frame.DataFrame
    :param col_name: name of column
    :type  col_name: str
    :param operations: list of operations to perform on the certain column
    :type  operations: list
    :returns: transformed dataframe 
    :rtype:   pandas.core.frame.DataFrame
    """

    col = df[col_name]

    for operation in operations:
        if operation == 'drop':
            return df.drop(col_name, axis=1)

        elif str(col.dtype) in {'int8', 'int16', 'int32', 'float64'}:
            if operation == 'log':
                col = np.log(1 + col)  # to make sure no divide by zero
            elif operation == 'box cox':
                col = ss.boxcox(col + 0.001)  # to make sure no divide by zero
            elif operation == "drop0":
                df = df[col != 0]
                col = col[col != 0]
            elif operation == "absneg":
                col = col.abs()
            elif operation == "median0":
                from sklearn.preprocessing import Imputer
                col[col == 0] = np.nan
                imputer = Imputer(strategy="median")
                col = imputer.fit_transform(col.values.reshape(-1, 1))
            elif operation.split('_')[0] == 'binning':
                num = int(operation.split('_')[1])
                quantile_list = [i / (num - 1) for i in range(num)]
                print(quantile_list)
                print(quantile_list[1:])
                
                df["DROP_" + col_name] = pd.qcut(
                    col,
                    q=quantile_list,
                    duplicates='raise',
                )
                col = pd.qcut(
                    col,
                    q=quantile_list,
                    duplicates='raise',
                    labels=quantile_list[1:]
                )
            elif operation.split('_')[0] == 'outlierZ':
                z = np.abs(ss.zscore(col))
                keep_values = z < float(operation.split('_')[1])
                df = df[keep_values]
                col = col[keep_values]
            elif operation == "shiftmin":
                col = col - col.min()
            else:
                raise ValueError('Not an available operation for numerics')

        elif str(col.dtype) in {'datetime64[ns]'}:
            if operation == "finddays":
                col = (col - min(col)).dt.days

        elif str(col.dtype) in {'category', 'object'}:
            if operation.split('_')[0] == "cbinning":
                num = float(operation.split('_')[1])
                value_counts = col.value_counts()
                x = col.replace(value_counts)
                df[col_name][df[col_name] == '0'] = np.nan
                df[col_name] = df[col_name].cat.add_categories(['OTHER'])
                df[col_name] = df[col_name].fillna('OTHER')
                df.loc[x < num, col_name] = 'OTHER'
                return df
            elif operation == "mostcommon":
                most_common = col.value_counts().index[0]
                col = col.fillna(most_common)
            else:
                raise ValueError(
                    'Not an available operation for categoricals or objects')

        else:
            raise ValueError('Not an available data type')

    df[col_name] = col

    return df

In [110]:
def perform_operations_with_classes(df, list_of_classes):
    for col_class in list_of_classes:
        df = perform_operations(df, col_class.name, col_class.operations)
    return df
    
#testing_all = perform_operations_with_classes(train_X, list_of_classes)

In [127]:
train_X.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
3607,454,a,2013-02-27,Dmdd,2092,DMDD,35.426020,-4.227446,Narmo,0,Internal,Bashnet Kati,Manyara,21,1,Babati,Bashinet,160,True,GeoData Consultants Ltd,Water Board,NaN,True,1998,gravity,gravity,gravity,water board,user-group,pay per bucket,per bucket,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
50870,510,a,2011-03-17,Cmsr,0,Gove,35.510074,-5.724555,Lukali,0,Internal,Lukali,Dodoma,1,6,Bahi,Lamaiti,0,True,GeoData Consultants Ltd,VWC,NaN,True,0,india mark ii,india mark ii,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
20413,14146,a,2011-07-10,Kkkt,0,KKKT,32.499866,-9.081222,Mahakama,0,Lake Rukwa,Chawalikozi,Mbeya,12,6,Mbozi,Ndalambo,0,True,GeoData Consultants Ltd,VWC,NaN,False,0,other,other,other,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,other,other
52806,47410,a,2011-04-12,NaN,0,NaN,34.060484,-8.830208,Shule Ya Msingi Chosi A,0,Rufiji,Shuleni,Mbeya,12,7,Mbarali,Chimala,0,True,GeoData Consultants Ltd,VWC,NaN,True,0,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,insufficient,insufficient,river,river/lake,surface,communal standpipe,communal standpipe
50091,1288,e,2011-04-05,Ki,1023,Ki,37.032690,-6.040787,Kwa Mjowe,0,Wami / Ruvu,Ngholong,Morogoro,5,1,Kilosa,Chakwale,120,True,GeoData Consultants Ltd,VWC,NaN,True,1997,other,other,other,vwc,user-group,pay when scheme fails,on failure,salty,salty,enough,enough,shallow well,shallow well,groundwater,other,other

In [142]:
#perform_operations(train_X, 'id', ['drop']).head()
#perform_operations(train_X, 'amount_tsh', ['outlierZ_3'])#.head()
#perform_operations(train_X, 'amount_tsh', ['median0'])#.head()
#test = perform_operations(train_X, 'gps_height', ['absneg'])#.head()
#test = perform_operations(train_X, 'population', ['outlierZ'])#.head()
#test = perform_operations(train_X, 'construction_year', ['median0', 'shiftmin'])#.head()
#test = perform_operations(train_X, 'public_meeting', ["mostcommon"])#.head()
#test['public_meeting'].isnull().any()
test = perform_operations(train_X, 'amount_tsh', ['binning_2']).head()
test

[0.0, 1.0]
[1.0]

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,subvillage,region,region_code,district_code,lga,ward,population,public_meeting,recorded_by,scheme_management,scheme_name,permit,construction_year,extraction_type,extraction_type_group,extraction_type_class,management,management_group,payment,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,DROP_amount_tsh
3607,454,1.0,2013-02-27,Dmdd,2092,DMDD,35.426020,-4.227446,Narmo,0,Internal,Bashnet Kati,Manyara,21,1,Babati,Bashinet,160,True,GeoData Consultants Ltd,Water Board,NaN,True,1998,gravity,gravity,gravity,water board,user-group,pay per bucket,per bucket,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe,"(-0.001, 350000.0]"
50870,510,1.0,2011-03-17,Cmsr,0,Gove,35.510074,-5.724555,Lukali,0,Internal,Lukali,Dodoma,1,6,Bahi,Lamaiti,0,True,GeoData Consultants Ltd,VWC,NaN,True,0,india mark ii,india mark ii,handpump,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump,"(-0.001, 350000.0]"
20413,14146,1.0,2011-07-10,Kkkt,0,KKKT,32.499866,-9.081222,Mahakama,0,Lake Rukwa,Chawalikozi,Mbeya,12,6,Mbozi,Ndalambo,0,True,GeoData Consultants Ltd,VWC,NaN,False,0,other,other,other,vwc,user-group,never pay,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,other,other,"(-0.001, 350000.0]"
52806,47410,1.0,2011-04-12,NaN,0,NaN,34.060484,-8.830208,Shule Ya Msingi Chosi A,0,Rufiji,Shuleni,Mbeya,12,7,Mbarali,Chimala,0,True,GeoData Consultants Ltd,VWC,NaN,True,0,gravity,gravity,gravity,vwc,user-group,pay monthly,monthly,soft,good,insufficient,insufficient,river,river/lake,surface,communal standpipe,communal standpipe,"(-0.001, 350000.0]"
50091,1288,1.0,2011-04-05,Ki,1023,Ki,37.032690,-6.040787,Kwa Mjowe,0,Wami / Ruvu,Ngholong,Morogoro,5,1,Kilosa,Chakwale,120,True,GeoData Consultants Ltd,VWC,NaN,True,1997,other,other,other,vwc,user-group,pay when scheme fails,on failure,salty,salty,enough,enough,shallow well,shallow well,groundwater,other,other,"(-0.001, 350000.0]"

In [137]:
def drop_col_with_DROP(df):
    """
    Drop columns that have a name of DROP_XXX.
    
    :param df: dataframe
    :type  df: pandas.core.frame.DataFrame
    :returns: dataframe of dropped columns
    :rtype:   pandas.core.frame.DataFrame
    """
    
    for col in df.columns:
        if col.split('_')[0] == 'DROP':
            df = df.drop([col], axis=1)
    return df

In [138]:
from sklearn.base import BaseEstimator, TransformerMixin

class DataCleaning(BaseEstimator, TransformerMixin):
    """
    Class for performing data cleaning, so the same can be applied to the test case
    """
    
    def __init__(self, class_list=list_of_classes):
        self.class_list = class_list
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        X = drop_col_with_DROP(X)
        X_transformed = perform_operations_with_classes(X, self.class_list)
        return X_transformed

In [77]:
trans = DataCleaning()
testing_all = trans.transform(train_X)

[0.0, 0.25, 0.5, 0.75, 1.0]

/Users/jinli/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [78]:
testing_all.head()

,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,region,district_code,lga,population,public_meeting,scheme_management,permit,construction_year,extraction_type_class,management,payment_type,quality_group,quantity_group,source,waterpoint_type_group
3607,"(20.0, 350000.0]",3339,Dmdd,2092,OTHER,35.426020,-4.227446,Manyara,1,Babati,160,True,Water Board,True,38.0,gravity,water board,per bucket,good,insufficient,spring,communal standpipe
50870,"(-0.001, 20.0]",2626,Cmsr,0,Gove,35.510074,-5.724555,Dodoma,6,Bahi,0,True,VWC,True,40.0,handpump,vwc,never pay,good,enough,shallow well,hand pump
20413,"(-0.001, 20.0]",2741,Kkkt,0,KKKT,32.499866,-9.081222,Mbeya,6,Mbozi,0,True,VWC,False,40.0,other,vwc,never pay,good,enough,shallow well,other
52806,"(-0.001, 20.0]",2652,OTHER,0,OTHER,34.060484,-8.830208,Mbeya,7,Mbarali,0,True,VWC,True,40.0,gravity,vwc,monthly,good,insufficient,river,communal standpipe
50091,"(20.0, 350000.0]",2645,Ki,1023,OTHER,37.032690,-6.040787,Morogoro,1,Kilosa,120,True,VWC,True,37.0,other,vwc,on failure,salty,enough,shallow well,other

In [79]:
testing_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45517 entries, 3607 to 56422
Data columns (total 22 columns):
amount_tsh               45517 non-null category
date_recorded            45517 non-null int64
funder                   45517 non-null category
gps_height               45517 non-null int16
installer                45517 non-null category
longitude                45517 non-null float64
latitude                 45517 non-null float64
region                   45517 non-null category
district_code            45517 non-null category
lga                      45517 non-null category
population               45517 non-null int16
public_meeting           45517 non-null category
scheme_management        45517 non-null category
permit                   45517 non-null category
construction_year        45517 non-null float64
extraction_type_class    45517 non-null category
management               45517 non-null category
payment_type             45517 non-null category
quality_group            45517 non-null category
quantity_group           45517 non-null category
source                   45517 non-null category
waterpoint_type_group    45517 non-null category
dtypes: category(16), float64(3), int16(2), int64(1)
memory usage: 2.9 MB

In [80]:
def split_cat_num (df):
    """
    Split the dataframe into two dataframes, 
    where one contains the numeric datatypes 
    and the other contains categorical datatypes.
    
    :param df: dataframe
    :type  df: pandas.core.frame.DataFrame
    :returns: (df with numeric dtypes, df with categorical dtypes)
    :rtype:   (pandas.core.frame.DataFrame, pandas.core.frame.DataFrame)
    """
    
    col_names = set (df.columns)
    types = set ([str(dtype) for dtype in df.dtypes.values])
    
    num_cols = df.select_dtypes(include=['int8', 'int16', 'int32', 'int64', 'float64'])
    cat_cols = df.select_dtypes(include=['category'])
    
    num_col_names = set (num_cols.columns)
    cat_col_names = set (cat_cols.columns)
    
    missing_col_names = col_names.difference(num_col_names).difference(cat_col_names)
    
    if len (missing_col_names) != 0: 
        print ("Columns Missing:", missing_col_names)
    
    return list (num_cols.columns), list (cat_cols.columns)
    
num_cols, cat_cols = split_cat_num(testing_all)

In [81]:
cat_cols

['amount_tsh',
 'funder',
 'installer',
 'region',
 'district_code',
 'lga',
 'public_meeting',
 'scheme_management',
 'permit',
 'extraction_type_class',
 'management',
 'payment_type',
 'quality_group',
 'quantity_group',
 'source',
 'waterpoint_type_group']

In [84]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

num_pipeline = Pipeline([
        ('std_scaler', StandardScaler()),
    ])

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_cols),
        ("cat", OneHotEncoder(), cat_cols),
    ])

In [85]:
test = full_pipeline.fit_transform(testing_all)
test

TypeError: int() argument must be a string, a bytes-like object or a number, not 'pandas._libs.interval.Interval'

In [60]:
#full_pipeline.fit_transform(train_X)

In [74]:
testing_all

,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,region,district_code,lga,population,public_meeting,scheme_management,permit,construction_year,extraction_type_class,management,payment_type,quality_group,quantity_group,source,waterpoint_type_group
3607,"(20.0, 350000.0]",3339,Dmdd,2092,OTHER,35.426020,-4.227446,Manyara,1,Babati,160,True,Water Board,True,38.0,gravity,water board,per bucket,good,insufficient,spring,communal standpipe
50870,"(-0.001, 20.0]",2626,Cmsr,0,Gove,35.510074,-5.724555,Dodoma,6,Bahi,0,True,VWC,True,40.0,handpump,vwc,never pay,good,enough,shallow well,hand pump
20413,"(-0.001, 20.0]",2741,Kkkt,0,KKKT,32.499866,-9.081222,Mbeya,6,Mbozi,0,True,VWC,False,40.0,other,vwc,never pay,good,enough,shallow well,other
52806,"(-0.001, 20.0]",2652,OTHER,0,OTHER,34.060484,-8.830208,Mbeya,7,Mbarali,0,True,VWC,True,40.0,gravity,vwc,monthly,good,insufficient,river,communal standpipe
50091,"(20.0, 350000.0]",2645,Ki,1023,OTHER,37.032690,-6.040787,Morogoro,1,Kilosa,120,True,VWC,True,37.0,other,vwc,on failure,salty,enough,shallow well,other
16521,"(-0.001, 20.0]",2770,Hesawa,0,DWE,33.509112,-2.648505,Mwanza,2,Magu,0,True,VWC,True,40.0,handpump,vwc,never pay,salty,enough,shallow well,hand pump
52225,"(-0.001, 20.0]",3341,World Vision,0,World vision,33.731347,-3.284633,Shinyanga,2,Maswa,0,True,WUG,False,40.0,handpump,wug,other,good,seasonal,shallow well,hand pump
9440,"(-0.001, 20.0]",2630,OTHER,298,OTHER,36.864072,-7.935517,Morogoro,3,Kilombero,250,True,VWC,True,49.0,handpump,vwc,never pay,good,insufficient,shallow well,hand pump
41885,"(-0.001, 20.0]",2764,Government Of Tanzania,0,Government,33.423658,-2.606991,Mwanza,2,Magu,0,True,VWC,True,40.0,motorpump,vwc,never pay,good,enough,machine dbh,communal standpipe
54042,"(-0.001, 20.0]",3303,Government Of Tanzania,1141,DWE,30.381136,-4.640729,Kigoma,2,Kasulu,1520,True,Water authority,False,49.0,handpump,vwc,never pay,good,enough,shallow well,hand pump
2732,"(-0.001, 20.0]",2615,OTHER,306,DWE,38.558271,-5.132980,Tanga,2,Korogwe,500,True,VWC,False,48.0,other,vwc,never pay,good,dry,shallow well,other
36783,"(-0.001, 20.0]",2638,Government Of Tanzania,365,DWE,38.328047,-5.019618,Tanga,2,Korogwe,150,True,VWC,False,44.0,handpump,vwc,never pay,salty,insufficient,shallow well,hand pump
23198,"(-0.001, 20.0]",2607,Danida,1572,DWE,35.058371,-8.217479,Iringa,2,Mufindi,0,True,VWC,True,40.0,handpump,vwc,never pay,good,enough,hand dtw,hand pump
2624,"(-0.001, 20.0]",3324,Government Of Tanzania,0,Government,33.519376,-3.225549,Shinyanga,2,Maswa,0,True,VWC,False,40.0,other,vwc,never pay,good,enough,shallow well,other
35833,"(-0.001, 20.0]",3557,OTHER,1510,DWE,36.699314,-3.339683,Arusha,2,Arusha Rural,150,True,Parastatal,True,38.0,gravity,private operator,never pay,good,enough,spring,communal standpipe
22921,"(-0.001, 20.0]",2764,OTHER,0,OTHER,33.585410,-9.240969,Mbeya,4,Rungwe,0,True,VWC,True,40.0,gravity,vwc,annually,good,enough,spring,communal standpipe
20357,"(-0.001, 20.0]",2741,Hesawa,0,DWE,31.425592,-1.211074,Kagera,7,Misenyi,0,True,VWC,True,40.0,handpump,vwc,never pay,good,insufficient,shallow well,hand pump
35940,"(-0.001, 20.0]",2623,Bsf,0,OTHER,35.970383,-6.679067,Dodoma,4,Chamwino,0,True,VWC,True,40.0,motorpump,vwc,per bucket,good,insufficient,machine dbh,communal standpipe
8850,"(-0.001, 20.0]",3367,OTHER,1478,OTHER,36.922038,-3.261929,Arusha,7,Meru,95,True,Water Board,True,52.0,gravity,water board,unknown,good,enough,spring,communal standpipe
35806,"(-0.001, 20.0]",3339,OTHER,1588,OTHER,34.920112,-4.485898,Singida,2,Singida Rural,430,True,VWC,True,50.0,submersible,vwc,never pay,good,insufficient,machine dbh,communal standpipe
26971,"(-0.001, 20.0]",2634,OTHER,0,OTHER,33.143206,-9.342734,Mbeya,5,Ileje,0,True,VWC,False,40.0,gravity,vwc,unknown,good,insufficient,spring,communal standpipe
20066,"(-0.001, 20.0]",3323,Government Of Tanzania,0,DWE,33.168247,-4.453132,Tabora,1,Nzega,0,False,VWC,True,40.0,motorpump,vwc,never pay,good,insufficient,dam,communal standpipe
54408,"(-0.001, 20.0]",2753,OTHER,0,OTHER,32.955944,-2.533517,Mwanza,8,Missungwi,0,False,Parastatal,True,40.0,other,parastatal,never pay,good,enough,shallow well,other
19553,"(-0.001, 20.0]",3206,Government Of Tanzania,0,Government,33.143039,-3.883174,Shinyanga,3,Shinyanga Rural,0,True,VWC,True,40.0,other,vwc,never pay,good,enough,dam,communal standpipe
5354,"(-0.001, 20.0]",2622,Concern,2047,OTHER,34.539695,-9.252128,Iringa,4,Njombe,20,True,VWC,True,25.0,gravity,vwc,on failure,good,enough,spring,communal standpipe
38499,"(-0.001, 20.0]",2647,OTHER,0,OTHER,34.381677,-8.711973,Mbeya,7,Mbarali,0,False,Water Board,True,40.0,gravity,water board,never pay,colored,seasonal,river,communal standpipe
31196,"(-0.001, 20.0]",3315,OTHER,1052,OTHER,36.957172,-3.398525,Arusha,7,Meru,126,True,Water Board,True,43.0,gravity,water board,per bucket,good,insufficient,river,communal standpipe
17252,"(-0.001, 20.0]",2765,OTHER,0,OTHER,33.560490,-9.250031,Mbeya,4,Rungwe,0,True,VWC,True,40.0,gravity,vwc,never pay,good,insufficient,spring,communal standpipe
35979,"(-0.001, 20.0]",2748,OTHER,0,OTHER,33.808619,-9.182979,Mbeya,4,Rungwe,0,True,VWC,True,40.0,gravity,vwc,never pay,fluoride,enough,river,communal standpipe
45688,"(-0.001, 20.0]",3336,Netherlands,0,DWE,33.578379,-3.133621,Shinyanga,2,Maswa,0,True,WUG,False,40.0,handpump,wug,never pay,good,dry,shallow well,hand pump
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41434,"(20.0, 350000.0]",3338,Snv,709,DWE,36.047875,-10.987656,Ruvuma,5,Namtumbo,420,True,WUG,True,39.0,handpump,wug,annually,good,insufficient,shallow well,hand pump
27480,"(-0.001, 20.0]",3304,Finw,325,FinW,39.568105,-10.732531,Mtwara,4,Tandahimba,540,True,Water Board,True,22.0,submersible,vwc,per bucket,good,enough,machine dbh,communal standpipe
6396,"(-0.001, 20.0]",2620,Amref,11,AMREF,39.291278,-7.175521,Pwani,4,Mkuranga,300,True,VWC,False,43.0,handpump,vwc,never pay,good,enough,shallow well,hand pump
28693,"(-0.001, 20.0]",2630,Danida,1873,DWE,35.134450,-8.638220,Iringa,2,Mufindi,0,True,VWC,False,40.0,handpump,vwc,never pay,good,enough,shallow well,hand pump
19769,"(-0.001, 20.0]",2634,Government Of Tanzania,0,Gover,36.494383,-7.108231,Dodoma,1,Mpwapwa,0,True,VWC,True,40.0,gravity,vwc,never pay,colored,insufficient,spring,communal standpipe
53707,"(-0.001, 20.0]",3365,Germany,1451,OTHER,36.911873,-3.251236,Arusha,7,Meru,400,True,WUA,False,53.0,gravity,wua,unknown,good,insufficient,rainwater harvesting,communal standpipe
17568,"(-0.001, 20.0]",3328,Danida,1679,DANIDA,30.048412,-4.496720,Kigoma,2,Kasulu,750,True,Water authority,True,44.0,gravity,water board,never pay,good,enough,spring,improved spring
39188,"(20.0, 350000.0]",3355,OTHER,73,OTHER,39.077297,-7.001628,Dar es Salaam,2,Ilala,100,True,Private operator,False,50.0,submersible,private operator,per bucket,salty,enough,machine dbh,communal standpipe
37819,"(20.0, 350000.0]",3334,Government Of Tanzania,691,DWE,37.298159,-3.566421,Manyara,4,Simanjiro,300,True,VWC,True,17.0,gravity,vwc,monthly,good,enough,spring,communal standpipe
5311,"(20.0, 350000.0]",3296,Norad,870,DWE,29.660516,-4.822412,Kigoma,3,Kigoma Rural,736,True,VWC,True,25.0,gravity,vwc,monthly,good,insufficient,river,communal standpipe
2433,"(20.0, 350000.0]",2616,Government Of Tanzania,330,DWE,36.821785,-8.915759,Morogoro,4,Ulanga,64,True,WUG,True,19.0,gravity,wug,monthly,good,enough,river,communal standpipe
56101,"(-0.001, 20.0]",3198,OTHER,0,DWE,32.008078,-3.650356,Shinyanga,5,Bukombe,0,True,WUG,True,40.0,handpump,wug,unknown,good,dry,shallow well,hand pump
769,"(-0.001, 20.0]",3357,OTHER,1033,OTHER,36.055479,-3.528026,Arusha,1,Monduli,1,False,Parastatal,True,40.0,submersible,parastatal,never pay,good,enough,machine dbh,communal standpipe
1685,"(-0.001, 20.0]",2620,World Bank,0,Gove,35.345622,-6.236176,Dodoma,6,Bahi,0,True,VWC,True,40.0,motorpump,vwc,per bucket,good,enough,machine dbh,communal standpipe
41090,"(-0.001, 20.0]",2633,World Bank,0,OTHER,36.644403,-6.249858,Dodoma,3,Kongwa,0,True,VWC,False,40.0,submersible,vwc,per bucket,salty,dry,machine dbh,communal standpipe
16023,"(-0.001, 20.0]",3294,OTHER,1618,OTHER,34.939963,-4.603470,Singida,2,Singida Rural,1,True,VWC,True,30.0,handpump,vwc,never pay,good,insufficient,shallow well,hand pump
44131,"(-0.001, 20.0]",2623,Bsf,0,DWE,35.238399,-5.172737,Dodoma,1,Kondoa,0,True,VWC,False,40.0,motorpump,vwc,per bucket,good,enough,machine dbh,communal standpipe
47191,"(-0.001, 20.0]",3315,Government Of Tanzania,1140,RWE,36.894763,-3.387685,Arusha,7,Meru,120,True,VWC,True,35.0,gravity,vwc,unknown,good,insufficient,unknown,communal standpipe
21962,"(-0.001, 20.0]",2614,Government Of Tanzania,1254,DWE,38.327642,-4.457114,Tanga,1,Lushoto,1,True,VWC,True,48.0,gravity,vwc,never pay,good,enough,spring,communal standpipe
37194,"(-0.001, 20.0]",2607,Kkkt,1922,Commu,34.230959,-9.369277,Iringa,3,Makete,0,True,VWC,False,40.0,gravity,vwc,never pay,good,enough,spring,communal standpipe
16850,"(-0.001, 20.0]",2642,OTHER,0,OTHER,38.466952,-5.172985,Tanga,2,Korogwe,1000,True,VWC,True,48.0,handpump,vwc,per bucket,good,insufficient,shallow well,hand pump
6265,"(-0.001, 20.0]",2619,Bsf,0,Gove,35.547568,-6.336433,Dodoma,6,Bahi,0,True,VWC,True,40.0,motorpump,vwc,per bucket,good,enough,machine dbh,communal standpipe
54886,"(20.0, 350000.0]",3324,OTHER,1509,OTHER,34.526739,-4.412383,Singida,1,Iramba,458,True,VWC,True,48.0,handpump,vwc,on failure,good,enough,machine dbh,hand pump
11284,"(-0.001, 20.0]",3355,Government Of Tanzania,1312,DWE,37.335656,-3.249673,Kilimanjaro,4,Moshi Rural,1,False,VWC,True,12.0,gravity,vwc,never pay,good,insufficient,spring,other
44732,"(-0.001, 20.0]",3527,Oikos E.Afrika,1584,Community,36.828101,-3.187085,Arusha,7,Meru,120,True,VWC,True,46.0,gravity,wug,unknown,good,enough,spring,communal standpipe
54343,"(20.0, 350000.0]",2629,Dhv,327,DWE,36.367112,-8.774761,Morogoro,4,Ulanga,255,True,Water Board,True,35.0,gravity,wug,monthly,good,enough,river,communal standpipe
38158,"(20.0, 350000.0]",2619,Danida,1743,DANID,34.531524,-9.769604,Iringa,5,Ludewa,35,True,VWC,False,28.0,gravity,vwc,annually,good,seasonal,spring,communal standpipe
860,"(-0.001, 20.0]",2622,OTHER,13,OTHER,38.974416,-5.420823,Tanga,5,Pangani,1000,False,Private operator,False,45.0,other,private operator,never pay,good,insufficient,shallow well,other
15795,"(-0.001, 20.0]",3220,Rwssp,0,WEDECO,34.316586,-3.107161,Shinyanga,6,Meatu,0,True,WUG,True,40.0,handpump,wug,never pay,good,enough,shallow well,hand pump
56422,"(-0.001, 20.0]",3336,Government Of Tanzania,1290,District council,37.626401,-3.211457,Kilimanjaro,1,Rombo,1,True,Company,True,16.0,gravity,company,monthly,good,enough,spring,communal standpipe

In [86]:
trial = testing_all.drop(['amount_tsh'], axis=1)

In [88]:
tnum_cols, tcat_cols = split_cat_num(trial)
full_pipeline = ColumnTransformer([
        ("num", num_pipeline, tnum_cols),
        ("cat", OneHotEncoder(), tcat_cols),
    ])
ttest = full_pipeline.fit_transform(testing_all)

In [91]:
ttest.toarray().shape

(45517, 428)

In [96]:
"cat".categories_

AttributeError: 'str' object has no attribute 'categories_'

In [108]:
z = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
z[1:]

[0.2, 0.4, 0.6, 0.8, 1.0]